name: 'Minio Upload without Docker'
description: 'Upload any files to your MinIO storage.'
author: 'CKylinMC'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  endpoint:
    description: 'MinIO endpoint'
    required: true
    default: ''
  port:
    description: 'Custom port number, default set to 443.'
    default: '443'
  accesskey:
    description: 'AccessKey of your MinIO storage.'
    required: true
    default: ''
  secretkey:
    description: 'SecretKey of your MinIO storage.'
    required: true
    default: ''
  bucketname:
    description: 'Name of your bucket'
    required: true
    default: 'common'
  usessl:
    description: 'Set this value to true to enable secure (HTTPS) access'
    default: true
  source:
    description: 'Path to files you want to upload.'
    required: true
    default: '.'
  dest:
    description: 'Path to file you want upload to. (Target FILE name!)'
    required: true
    default: '/'
outputs:
  status:
    description: 'Will be "successed" or "failed"'
runs:
  using: 'node16'
  main: 'dist/index.js'
